name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk zlib1g-dev libtool autoconf automake cmake

      - name: Install Buildozer & Cython
        run: |
          pip install "cython<3.0.0" buildozer

      - name: Configure and Build APK
        run: |
          echo "y" | buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,pyjnius/g' buildozer.spec
          sed -i 's/android.api = 31/android.api = 33/g' buildozer.spec
          sed -i 's/#android.permissions = INTERNET/android.permissions = RECORD_AUDIO, CALL_PHONE, QUERY_ALL_PACKAGES, INTERNET/g' buildozer.spec
          sed -i 's/android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/g' buildozer.spec
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jarvis-apk
          path: bin/*.apk
          
